#!/usr/bin/env python3
"""Prove the PDF and the HTML are the same document, instead of assuming it.

The client note is approved on screen and sent as a PDF. Those two used to be
different designs, and nothing in the pipeline noticed: the PDF rendered without
error, looked plausible on its own, and only side-by-side did it turn out to be a
one-column white-paper version of a two-column tinted page.

So this script renders both and measures the difference:

  1. the HTML at the PDF's own page width, full height
  2. the PDF, rasterised at the same scale
  3. the fraction of pixels that differ by more than a small tolerance

A near-zero score is the goal. What the score does NOT need to be is zero:
antialiasing, image resampling and font hinting differ between a screen raster
and a PDF raster, so a few percent of pixels always disagree slightly. What
matters is the SHAPE: a layout that reflowed, a background that dropped out or a
figure that vanished moves this number into the tens of percent, and the diff
image shows exactly where.

Usage:
    python compare-pdf-to-html.py "<releases.out>/<version> - <date>/client.html"
    ... --out-dir DIR      where to write html.png / pdf.png / diff.png
                           (default: <release folder>/compare/ - scratch output, never committed)
    ... --max-diff 0.08    fail above this fraction of differing pixels

Needs Pillow, pypdfium2, and a configured clone carrying node_modules/playwright-core
(the same browser the capture and the PDF render use).
"""
from __future__ import annotations

import argparse
import re
import shutil
import subprocess
import sys

sys.dont_write_bytecode = True  # a skill does not litter its own folder with __pycache__

import tempfile
from pathlib import Path

from _hub import Config, find_hub, launch_options, node_env, node_modules_dir, python_playwright, utf8_stdio

NODE_DRIVER = r"""
// Generated by compare-pdf-to-html.py. Shoots the HTML exactly as the PDF is
// laid out: same width, print media, light theme.
const path = require('path');
const url = require('url');
const { chromium } = require('playwright-core');

const [, , htmlPath, outPath, widthArg] = process.argv;
const width = Math.round(Number(widthArg));

(async () => {
  const launch = {};
  if (process.env.UX_EXECUTABLE_PATH) launch.executablePath = process.env.UX_EXECUTABLE_PATH;
  if (process.env.UX_BROWSER_CHANNEL) launch.channel = process.env.UX_BROWSER_CHANNEL;
  const browser = await chromium.launch(launch);
  const context = await browser.newContext({ colorScheme: 'light' });
  const page = await context.newPage();
  await page.setViewportSize({ width, height: 1400 });
  await page.goto(url.pathToFileURL(path.resolve(htmlPath)).href, { waitUntil: 'load' });
  await page.evaluate(() => document.fonts && document.fonts.ready);
  await page.waitForTimeout(600);
  // Print media, because that is what the PDF is: the comparison is "does the
  // PDF match the page", not "does print media match screen media".
  await page.emulateMedia({ media: 'print' });
  // Short viewport, so a full-page shot of a short note is the content's own
  // height rather than the viewport's - the same measurement the PDF uses.
  await page.setViewportSize({ width, height: 200 });
  await page.waitForTimeout(250);
  await page.screenshot({ path: outPath, fullPage: true });
  await browser.close();
})().catch(e => { console.error(e.message); process.exit(1); });
"""


def shoot_python(src: Path, out: Path, width: float) -> bool:
    """The NODE_DRIVER steps through the Python package."""
    from playwright.sync_api import sync_playwright
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(**launch_options())
            page = browser.new_context(color_scheme="light").new_page()
            page.set_viewport_size({"width": round(width), "height": 1400})
            page.goto(src.resolve().as_uri(), wait_until="load")
            page.evaluate("() => document.fonts && document.fonts.ready")
            page.wait_for_timeout(600)
            page.emulate_media(media="print")
            page.set_viewport_size({"width": round(width), "height": 200})
            page.wait_for_timeout(250)
            page.screenshot(path=str(out), full_page=True)
            browser.close()
    except Exception as err:
        print(f"  note: Python Playwright could not shoot the HTML ({str(err).splitlines()[0][:300]})",
              file=sys.stderr)
        return False
    return out.is_file()


def shoot_html(src: Path, out: Path, width: float, cfg: Config) -> None:
    if python_playwright() and shoot_python(src, out, width):
        return
    modules = node_modules_dir(cfg)
    if modules is None or not shutil.which("node"):
        raise SystemExit(
            "needs the Python `playwright` package, or node plus a playwright-core on NODE_PATH "
            "or in a configured clone - the same browser the PDF render uses"
        )
    with tempfile.TemporaryDirectory() as tmp:
        driver = Path(tmp) / "compare-note.driver.cjs"
        driver.write_text(NODE_DRIVER, encoding="utf-8")
        proc = subprocess.run(
            ["node", str(driver), str(src.resolve()), str(out.resolve()), str(width)],
            cwd=tmp, env=node_env(modules), capture_output=True, text=True, errors="replace",
        )
    if proc.returncode != 0 or not out.is_file():
        raise SystemExit(f"FAIL: could not screenshot the HTML\n{(proc.stderr or proc.stdout)[-600:]}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Compare the rendered PDF against the HTML.")
    parser.add_argument("html", help="path to the client note HTML")
    parser.add_argument("--pdf", help="the PDF (default: the HTML's name with .pdf)")
    parser.add_argument("--out-dir", help="where to write the three PNGs")
    parser.add_argument("--max-diff", type=float, default=0.08,
                        help="fail above this fraction of differing pixels (default 0.08)")
    parser.add_argument("--hub", help="hub root (default: walk up from the current directory)")
    args = parser.parse_args()
    utf8_stdio()
    cfg = Config(find_hub(args.hub, also_from=Path(args.html).parent))

    src = Path(args.html)
    pdf = Path(args.pdf) if args.pdf else src.with_suffix(".pdf")
    for path in (src, pdf):
        if not path.is_file():
            raise SystemExit(f"no such file: {path}")

    try:
        from PIL import Image, ImageChops
        import pypdfium2 as pdfium
    except ImportError as err:
        raise SystemExit(f"needs Pillow and pypdfium2: {err}")

    # Next to the note, so the three PNGs are easy to open - and scratch: the
    # release folder's compare/ is never committed.
    out_dir = Path(args.out_dir) if args.out_dir else src.parent / "compare"
    out_dir.mkdir(parents=True, exist_ok=True)

    doc = pdfium.PdfDocument(str(pdf))
    pages = len(doc)
    width_pt, height_pt = doc[0].get_size()
    width_px, height_px = width_pt / 0.75, height_pt / 0.75
    print(f"PDF: {pages} page(s), {width_px:.0f}x{height_px:.0f}px")
    if pages != 1:
        print("  note: comparing page 1 only - a paginated PDF cannot match a "
              "continuously scrolling page, by construction.")

    pdf_png = out_dir / "pdf.png"
    # 1/0.75: PDF points are 72 to the inch and CSS pixels 96, so this rasterises
    # the page at exactly the CSS pixel size the screenshot is taken at. Anything
    # less means comparing an upscaled raster against a native one, and the
    # resampling alone costs several percent.
    doc[0].render(scale=1 / 0.75).to_pil().convert("RGB").save(pdf_png)

    html_png = out_dir / "html.png"
    shoot_html(src, html_png, width_px, cfg)

    shot = Image.open(html_png).convert("RGB")
    printed = Image.open(pdf_png).convert("RGB")
    print(f"HTML: {shot.width}x{shot.height}px   PDF page 1: {printed.width}x{printed.height}px")

    if shot.width != printed.width:
        printed = printed.resize((shot.width, round(printed.height * shot.width / printed.width)),
                                 Image.LANCZOS)

    height_gap = abs(shot.height - printed.height)
    if height_gap > max(24, shot.height * 0.02):
        print(f"  WARN: the two differ by {height_gap}px in height. Either the PDF is "
              "paginated or the layout reflowed - the pixel score below is not meaningful "
              "until that is fixed.")

    # Compare the overlapping region; a height difference is already reported.
    height = min(shot.height, printed.height)
    a = shot.crop((0, 0, shot.width, height))
    b = printed.crop((0, 0, shot.width, height))

    diff = ImageChops.difference(a, b).convert("L")
    # A tolerance of 24/255 per channel: below that is resampling and hinting,
    # not a design difference. Anything structural is far above it.
    mask = diff.point(lambda v: 255 if v > 24 else 0)
    differing = sum(mask.histogram()[255:])
    total = shot.width * height
    score = differing / total
    mask.save(out_dir / "diff.png")

    print(f"differing pixels: {differing:,} / {total:,} = {score:.2%}")
    print(f"  html: {html_png}")
    print(f"  pdf:  {pdf_png}")
    print(f"  diff: {out_dir / 'diff.png'}  (white = differs)")

    if score > args.max_diff:
        print(f"\nFAIL: {score:.2%} of pixels differ, over the {args.max_diff:.0%} threshold. "
              "Open diff.png - a solid block means a whole region moved or dropped out.")
        return 1
    print(f"\npass: the PDF and the HTML agree within {args.max_diff:.0%}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
