#!/usr/bin/env python3
"""Render the client release note to PDF at the page's own width.

Chrome does the rendering rather than a Python PDF library because a note can be
in any script: Arabic-script glyph joining, ZWNJ handling, RTL bidi and complex
shaping are all required somewhere, and Blink already does them. A generic PDF
writer silently emits disconnected or reversed text and reports success.

**The PDF is the screen.** Not "a paper version of the screen" - the same
document, at the same width, with the same colours. Two decisions get it there:

  WIDTH comes from the stylesheet's @page size, so the layout never reflows.
  HEIGHT is measured from the content, so the PDF is ONE continuous page.

The height decision is the one worth explaining. Cutting the note into
page-sized sheets cannot be done without gaps: cards must not be sliced, so each
break leaves whatever space the next card could not fit into - in this note that
was 440px at the foot of page 1 and 700px at the foot of page 3, against an HTML
page that has no gaps anywhere. A single page removes the question. Text stays
selectable, the file stays small, and a viewer that has to put it on paper
scales it like any other oversized page. `--paginate` restores fixed sheets for
anyone who needs them.

ONE CONTINUOUS PAGE HAS A CEILING, THOUGH: about 8,192 CSS px. Viewers built on
pdf.js draw a page into a single canvas, and a canvas side cannot exceed
16,384px - which a Retina display reaches at twice the CSS height. Past that the
PDF is still a valid file, still passes every check in this skill, and opens to
a blank window. A note that long has to be rendered with `--paginate`; this
script warns when a continuous render crosses the line.

Which is why this script drives Chrome through Playwright rather than
`chrome --headless --print-to-pdf`:

    THE COMMAND LINE CANNOT MEASURE THE CONTENT.

`--print-to-pdf` has no way to measure the note and size the page to it, and
no way to ask for `preferCSSPageSize`, so it prints whatever fixed page the
stylesheet (or, with no usable @page, the browser default - A4 portrait, about
688px of printable width, which collapses the two-column cards) gives it. The
continuous page, the one-page default, is out of reach. Measured, not assumed:
a file that reports `page: 840x1188pt` through Playwright has reported
`595x842pt` through the CLI.

Order of preference: the Python `playwright` package (no driver file), then a
Node playwright-core found via NODE_PATH or a configured clone, then the CLI -
which says loudly what it costs. All three honour UX_EXECUTABLE_PATH /
UX_BROWSER_CHANNEL, so a browser already on disk is used when the download is
blocked.

The font report checks what actually landed in the PDF against the design
system's own list - `allowed_families` in <design.build>/tokens.json, written by
brand-system's `brand.py build`, plus the mono stack - and names the character
that pulled in anything else.

Usage:
    python render-client-pdf.py "<releases.out>/<version> - <date>/client.html"
    ... --paginate     fixed sheets at the @page height, instead of one continuous page
    ... --hub <path>   hub root (default: walk up from the current directory)
"""
from __future__ import annotations

import argparse
import base64
import json
import os
import platform
import re
import shutil
import subprocess
import sys

sys.dont_write_bytecode = True  # a skill does not litter its own folder with __pycache__

import tempfile
import unicodedata
from pathlib import Path

from _hub import (BRAND_SCRIPTS, Config, find_hub, launch_options, node_env, node_modules_dir,
                  python_playwright, utf8_stdio)

GENERIC_FAMILIES = {"serif", "sans-serif", "monospace", "cursive", "fantasy", "system-ui",
                    "ui-monospace", "ui-sans-serif", "ui-serif", "-apple-system", "emoji", "math"}

CANDIDATES = [
    r"C:\Program Files\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Google\Chrome\Application\chrome.exe",
    r"C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe",
    r"C:\Program Files\Microsoft\Edge\Application\msedge.exe",
    "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
    "/usr/bin/google-chrome",
    "/usr/bin/chromium",
    "/usr/bin/chromium-browser",
]

NODE_DRIVER = r"""
// Generated by render-client-pdf.py. Runs from a temp dir; NODE_PATH points at
// a node_modules carrying playwright-core.
const path = require('path');
const url = require('url');
const { chromium } = require('playwright-core');

const [, , htmlPath, outPath, optionsJson] = process.argv;
const options = JSON.parse(optionsJson);

(async () => {
  const launch = {};
  if (process.env.UX_EXECUTABLE_PATH) launch.executablePath = process.env.UX_EXECUTABLE_PATH;
  if (process.env.UX_BROWSER_CHANNEL) launch.channel = process.env.UX_BROWSER_CHANNEL;
  const browser = await chromium.launch(launch);
  // The note has to print the same way for everyone, so the renderer is pinned
  // to the light theme rather than inheriting whatever this machine prefers.
  const context = await browser.newContext({ colorScheme: 'light' });
  const page = await context.newPage();
  // The viewport must be the page width, or the height measured below belongs to
  // a layout the PDF will not have.
  await page.setViewportSize({ width: Math.round(options.widthPx), height: 1400 });
  await page.goto(url.pathToFileURL(path.resolve(htmlPath)).href, { waitUntil: 'load' });

  // Chrome activates a webfont only once laid-out content uses it, and decides
  // mid-paint. Wait for the faces the page asked for before printing, or a face
  // that appears once - the Latin version string, the em dash - falls back.
  await page.evaluate(() => document.fonts && document.fonts.ready);
  await page.waitForTimeout(600);

  let height = options.height;
  if (!height) {
    // Measure under print media: the print block changes the body padding, and
    // measuring the screen layout leaves a sliver of a second page.
    await page.emulateMedia({ media: 'print' });
    // A short viewport, because documentElement.scrollHeight is never less than
    // the viewport: measured at 1400px tall, a short note is padded to 1400px
    // and the PDF ends in a band of empty wash.
    await page.setViewportSize({ width: Math.round(options.widthPx), height: 200 });
    await page.waitForTimeout(200);
    const measured = await page.evaluate(() => {
      const doc = document.documentElement;
      const body = document.body;
      return Math.ceil(Math.max(
        doc.scrollHeight, doc.getBoundingClientRect().height,
        body.scrollHeight, body.getBoundingClientRect().height
      ));
    });
    await page.emulateMedia({ media: null });
    // +2px: a fractional layout height rounds down into a second page holding
    // one line of nothing, and a stray blank page is exactly the kind of detail
    // that gets noticed in a document sent to a client.
    height = (measured + 2) + 'px';
    console.log('measured-height=' + height);
  }

  // THE PAGE BOX AND THE SHEET MUST AGREE.
  //
  // Passing width/height to page.pdf() sizes the SHEET, but Chrome still breaks
  // the document at the height in the stylesheet's own @page rule. Give it a
  // 2864px sheet while the CSS says 1584px and you get exactly that: three
  // pages, each with the content crammed into its top 55% and the rest blank.
  // Measured, not deduced - that was the first attempt at this.
  //
  // So the size is injected as a real @page rule (appended last, so it wins the
  // cascade - `!important` is ignored inside @page) and printed with
  // preferCSSPageSize, which makes the sheet follow the same rule.
  await page.addStyleTag({
    content: `@page { size: ${options.width} ${height}; margin: 0; }`
  });
  await page.pdf({
    path: outPath,
    printBackground: true,
    margin: { top: '0', right: '0', bottom: '0', left: '0' },
    preferCSSPageSize: true,
    displayHeaderFooter: false
  });
  await browser.close();
})().catch(e => {
  console.error(e.message);
  process.exit(1);
});
"""


def css_page_size(markup: str) -> tuple[str, str] | None:
    """Read `@page { size: <w> <h> }` so the stylesheet stays authoritative."""
    block = re.search(r"@page\s*\{([^}]*)\}", markup)
    if not block:
        return None
    size = re.search(r"size\s*:\s*([^;}]+)", block.group(1))
    if not size:
        return None
    parts = size.group(1).split()
    if len(parts) == 2 and all(re.fullmatch(r"[\d.]+(?:px|mm|cm|in|pt)", p) for p in parts):
        return parts[0], parts[1]
    return None


def uncovered_characters(markup: str) -> list:
    """Name the characters no embedded face can draw.

    The font report says *that* something fell back; this says *what*. It matters
    because the fallback is invisible on screen and the culprit is usually one
    character in a hundred lines: one "\u2190" in a "where to find it" line once
    pulled a system face into a whole PDF, because neither embedded face carried
    it - the primary face never had it, and the brand build subsets the Latin face
    down to the glyphs ordinary copy needs.

    Returns [] if fontTools is not installed - a missing check, not a pass.
    """
    try:
        from fontTools.ttLib import TTFont
    except ImportError:
        return []

    faces = re.findall(r"@font-face\s*\{(.*?)\}", markup, re.S)
    covered = set()
    for face in faces:
        family = re.search(r'font-family:\s*["\']?([^"\';]+)', face)
        payload = re.search(r"base64,([A-Za-z0-9+/=]+)", face)
        if not (family and payload):
            continue
        try:
            blob = base64.b64decode(payload.group(1))
            path = Path(tempfile.gettempdir()) / f"brand-{family.group(1)}-{len(blob)}.bin"
            path.write_bytes(blob)
            covered |= set(TTFont(str(path)).getBestCmap())
        except Exception:
            continue
    if not covered:
        return []

    text = re.sub(r"(?s)<style.*?</style>|<script.*?</script>|<!--.*?-->", " ", markup)
    text = re.sub(r"<[^>]+>", " ", text)
    missing = {}
    for char in text:
        if char.isspace() or ord(char) < 0x20 or ord(char) in covered:
            continue
        # Zero-width and directional marks are laid out, never drawn - no font
        # needs a glyph for them, so they are not evidence of a fallback.
        if unicodedata.category(char) in ("Cf", "Mn"):
            continue
        missing[char] = missing.get(char, 0) + 1
    return sorted(
        f"U+{ord(c):04X} {unicodedata.name(c, 'unnamed')} {c!r} x{n}" for c, n in missing.items()
    )


def brand_families(cfg: Config) -> tuple[list, str | None]:
    """(allowed family names, the family the body copy must land in).

    Allowed = tokens.json `allowed_families` (the embedded brand faces) plus the
    named faces of the mono stack. Required = the first allowed face in the body
    stack. Both come from the design system; nothing is hardcoded here.
    """
    tokens_path = cfg.brand_build() / "tokens.json"
    if not tokens_path.is_file():
        return [], None
    tokens = json.loads(tokens_path.read_text(encoding="utf-8"))
    allowed = list(tokens.get("allowed_families") or tokens.get("embedded_weights") or [])
    common = (tokens.get("roles") or {}).get("common") or {}

    def stack(value: str) -> list:
        names = [part.strip().strip("'\"") for part in (value or "").split(",")]
        return [n for n in names if n and n.lower() not in GENERIC_FAMILIES]

    for name in stack(common.get("font-mono", "")):
        if name not in allowed:
            allowed.append(name)
    required = next((n for n in stack(common.get("font-body", "")) if n in allowed), None)
    return allowed, required


def find_browser() -> str:
    """The browser for the CLI fallback: UX_EXECUTABLE_PATH, then UX_BROWSER_CHANNEL, then PATH."""
    explicit = os.environ.get("UX_EXECUTABLE_PATH")
    if explicit:
        if not Path(explicit).exists():
            raise SystemExit(f"UX_EXECUTABLE_PATH={explicit} does not exist")
        return explicit
    channel = (os.environ.get("UX_BROWSER_CHANNEL") or "").lower()
    names = ("chrome", "google-chrome", "chromium", "msedge")
    if channel:
        names = tuple(n for n in names if channel.split("-")[0] in n) or names
    for name in names:
        found = shutil.which(name)
        if found:
            return found
    for path in CANDIDATES:
        if channel and channel.split("-")[0] not in path.lower():
            continue
        if Path(path).exists():
            return path
    raise SystemExit(
        "No Chrome or Edge found. Set UX_EXECUTABLE_PATH, install one, or print the HTML to "
        "PDF from a browser (the print stylesheet is already correct)."
    )


def win_path(path: Path) -> str:
    """Chrome on Windows needs a native path even when launched from Git Bash."""
    resolved = str(path.resolve())
    if platform.system() == "Windows":
        return resolved.replace("/", "\\")
    return resolved


def to_px(length: str) -> float:
    """CSS length -> px, at the 96dpi CSS reference Chrome prints against."""
    value = float(re.match(r"([\d.]+)", length).group(1))
    unit = length[len(re.match(r"[\d.]+", length).group(0)):] or "px"
    return value * {"px": 1, "pt": 96 / 72, "in": 96, "cm": 96 / 2.54, "mm": 96 / 25.4}[unit]


def render_with_python_playwright(src: Path, out: Path, size: tuple[str, str],
                                  paginate: bool) -> bool:
    """The same steps as NODE_DRIVER, through the Python package. See the driver's comments."""
    from playwright.sync_api import sync_playwright

    width_px = round(to_px(size[0]))
    try:
        with sync_playwright() as pw:
            browser = pw.chromium.launch(**launch_options())
            context = browser.new_context(color_scheme="light")
            page = context.new_page()
            page.set_viewport_size({"width": width_px, "height": 1400})
            page.goto(src.resolve().as_uri(), wait_until="load")
            page.evaluate("() => document.fonts && document.fonts.ready")
            page.wait_for_timeout(600)
            height = size[1] if paginate else None
            if not height:
                page.emulate_media(media="print")
                page.set_viewport_size({"width": width_px, "height": 200})
                page.wait_for_timeout(200)
                measured = page.evaluate("""() => {
                    const doc = document.documentElement, body = document.body;
                    return Math.ceil(Math.max(doc.scrollHeight, doc.getBoundingClientRect().height,
                                              body.scrollHeight, body.getBoundingClientRect().height));
                }""")
                page.emulate_media(media=None)
                height = f"{measured + 2}px"
            page.add_style_tag(content=f"@page {{ size: {size[0]} {height}; margin: 0; }}")
            page.pdf(path=str(out), print_background=True, prefer_css_page_size=True,
                     margin={"top": "0", "right": "0", "bottom": "0", "left": "0"},
                     display_header_footer=False)
            browser.close()
    except Exception as err:  # a missing browser build, a blocked download
        print(f"  note: Python Playwright could not render ({str(err).splitlines()[0][:300]}); "
              "trying the next renderer.", file=sys.stderr)
        return False
    return out.is_file() and out.stat().st_size > 0


def render_with_node_playwright(src: Path, out: Path, size: tuple[str, str],
                                paginate: bool, modules: Path | None) -> bool:
    """Print through a Node playwright-core, run from a temp dir with NODE_PATH set."""
    if modules is None or not shutil.which("node"):
        return False
    with tempfile.TemporaryDirectory() as tmp:
        driver = Path(tmp) / "release-pdf.driver.cjs"
        driver.write_text(NODE_DRIVER, encoding="utf-8")
        proc = subprocess.run(
            ["node", str(driver), str(src.resolve()), str(out.resolve()),
             json.dumps({
                 "width": size[0],
                 "widthPx": to_px(size[0]),
                 # No height means "measure the content" - one continuous page.
                 "height": size[1] if paginate else None,
             })],
            cwd=tmp, env=node_env(modules), capture_output=True, text=True, errors="replace",
        )
    if proc.returncode != 0 or not out.is_file() or out.stat().st_size == 0:
        message = (proc.stderr or proc.stdout).strip()[-400:]
        print(f"  note: Node Playwright could not render ({message}).", file=sys.stderr)
        return False
    return True


def render_with_cli(src: Path, out: Path) -> None:
    browser = find_browser()
    cmd = [
        browser,
        "--headless",
        "--disable-gpu",
        "--no-sandbox",
        "--no-pdf-header-footer",
        # Give webfonts a moment to load; without it the first render can fall
        # back mid-paint and ship a PDF in the wrong face.
        "--virtual-time-budget=4000",
        f"--print-to-pdf={win_path(out)}",
        win_path(src),
    ]
    proc = subprocess.run(cmd, capture_output=True, text=True, errors="replace")
    if not out.is_file() or out.stat().st_size == 0:
        print(proc.stderr.strip()[-800:], file=sys.stderr)
        raise SystemExit(f"FAIL: {out} was not written")


def main() -> int:
    parser = argparse.ArgumentParser(description="Render the client release note to PDF.")
    parser.add_argument("html", help="path to the client note HTML")
    parser.add_argument("--out", help="output PDF (default: alongside the HTML, .pdf)")
    parser.add_argument("--paginate", action="store_true",
                        help="cut the note into fixed sheets at the @page height, accepting "
                             "the gaps that leaves, instead of one continuous page")
    parser.add_argument("--hub", help="hub root (default: walk up from the current directory)")
    args = parser.parse_args()
    utf8_stdio()
    cfg = Config(find_hub(args.hub, also_from=Path(args.html).parent))

    src = Path(args.html)
    if not src.is_file():
        raise SystemExit(f"no such file: {src}")

    markup = src.read_text(encoding="utf-8")

    # Without a print block the PDF falls back to A4 and reflows into a layout
    # nobody designed. Hard stop rather than a warning: the resulting file looks
    # finished, which is what makes it dangerous.
    if not re.search(r"@media\s+print", markup):
        raise SystemExit("FAIL: no @media print block - the PDF will not look like the page.")
    if not re.search(r"print-color-adjust\s*:\s*exact", markup.replace("\n", " ")):
        print(
            "WARN: print-color-adjust: exact is missing - Chrome will drop the wash and the "
            "card surfaces, and the PDF will print on bare white.",
            file=sys.stderr,
        )

    size = css_page_size(markup)
    if not size:
        print("WARN: @page declares no usable `size` - the PDF will be A4 and the two-column "
              "cards will collapse. Set e.g. `size: 1120px 1584px`.", file=sys.stderr)

    out = Path(args.out) if args.out else src.with_suffix(".pdf")
    out.parent.mkdir(parents=True, exist_ok=True)

    mode = "paginated" if args.paginate else "one continuous page"
    how = None
    if size and python_playwright() and render_with_python_playwright(src, out, size, args.paginate):
        how = f"python playwright, {mode}"
    elif size and render_with_node_playwright(src, out, size, args.paginate, node_modules_dir(cfg)):
        how = f"node playwright, {mode}"
    else:
        print("  WARN: no Playwright could render, so this falls back to the chrome command "
              "line - it cannot measure the content, so the PDF is a fixed page, not the "
              "continuous one. Install the Python `playwright` package.", file=sys.stderr)
        render_with_cli(src, out)
        how = "chrome CLI (fixed page)"

    blob = out.read_bytes()
    pages = len(re.findall(rb"/Type\s*/Page[^s]", blob))
    # /MediaBox [0 0 w h] in PDF points, 72pt to the inch against CSS's 96px.
    box = re.search(rb"/MediaBox\s*\[\s*0\s+0\s+([\d.]+)\s+([\d.]+)\s*\]", blob)
    fonts = sorted({name.decode("ascii", "replace") for name in
                    re.findall(rb"/BaseFont\s*/([A-Za-z0-9+#-]+)", blob)})

    print(f"wrote {out} ({out.stat().st_size:,} bytes) via {how}")
    print(f"  pages: {pages}")
    if box:
        width, height = float(box.group(1)), float(box.group(2))
        print(f"  page:  {width:.0f}x{height:.0f}pt ({width / 0.75:.0f}x{height / 0.75:.0f}px)")
        if width / 0.75 < 1000:
            print(f"  WARN: the page is only {width / 0.75:.0f}px wide - narrower than the "
                  "layout, so the cards have collapsed to one column and the PDF no longer "
                  "matches the page.", file=sys.stderr)
        # A CONTINUOUS PAGE CAN BE TOO TALL TO RENDER AT ALL, and this fails
        # completely silently: the file is valid, every check here passes, and
        # the viewer simply shows nothing.
        #
        # The PDF spec allows 200in (14,400pt), so the file is legal. The limit
        # that actually bites is the VIEWER's: pdf.js - and everything built on
        # it, including browser previews and the VS Code PDF extensions -
        # rasterises a page into one canvas, and Skia/WebKit cap a canvas at
        # 16,384px on a side. On a Retina display the canvas is devicePixelRatio
        # (2) times the CSS height, so the real ceiling is 8,192 CSS px.
        #
        # Measured: one long feature note came out 10,148px tall, needed a
        # 2,240x20,296 canvas, and would not display. Every note that did
        # display was under 2,900px. pdfium rasterises the same file happily, so
        # checking it locally does NOT catch this - only a real viewer does.
        #
        # Past the ceiling, --paginate is the answer: cards do not split, so the
        # breaks cost some whitespace at a page foot - a cosmetic price for a
        # document that renders at all.
        css_h = height / 0.75
        if not args.paginate and css_h * 2 > 16384:
            print(f"  WARN: the page is {css_h:.0f}px tall. A pdf.js/canvas viewer on a "
                  f"Retina display needs a {width / 0.75 * 2:.0f}x{css_h * 2:.0f} canvas to "
                  "draw it, over the 16,384px maximum canvas side - so this PDF will open to "
                  "a BLANK viewer while remaining a perfectly valid file. Re-render with "
                  "--paginate.", file=sys.stderr)
    if not args.paginate and pages != 1:
        print(f"  WARN: {pages} pages from a continuous render - the content height was "
              "mis-measured, so there is a near-empty page in the file.", file=sys.stderr)
    print(f"  fonts: {', '.join(fonts) or 'none found'}")

    # A font that fails to load does not error - it silently falls back, and the
    # PDF still looks plausible. Three ways that happens, all seen for real:
    #   * a CFF-flavoured webfont, which Chrome will not embed in a PDF at all
    #   * a face used by content Chrome has not laid out when printing begins
    #   * a character in no embedded subset
    # So check what actually landed against the design system's own list.
    allowed, required = brand_families(cfg)
    norm = lambda name: re.sub(r"[^a-z0-9]", "", name.lower())
    if required and fonts and not any(norm(f.split("+", 1)[-1]).startswith(norm(required)) for f in fonts):
        print(f"  WARN: {required} (the first face of --ds-font-body) is not embedded - "
              "the copy is in a fallback face.", file=sys.stderr)

    # The brand toolkit owns the verdict on which faces are on-brand; this script
    # adds the one thing it cannot know - which character in THIS note pulled a
    # stranger in.
    off_brand = False
    brand_py = BRAND_SCRIPTS / "brand.py"
    if brand_py.is_file():
        proc = subprocess.run([sys.executable, str(brand_py), "pdf-fonts", str(out.resolve())],
                              cwd=cfg.hub, capture_output=True, text=True,
                              encoding="utf-8", errors="replace")
        for line in (proc.stdout + proc.stderr).strip().splitlines():
            print(f"  brand: {line}")
        off_brand = proc.returncode != 0
    elif allowed:
        print("  note: brand-system's brand.py is not installed next to this skill; checking "
              f"against tokens.json allowed_families ({', '.join(allowed)})", file=sys.stderr)
        strangers = [f for f in fonts
                     if not any(norm(f.split("+", 1)[-1]).startswith(norm(a)) for a in allowed)]
        if strangers:
            print(f"  WARN: non-brand font(s) in the PDF: {', '.join(strangers)}.", file=sys.stderr)
        off_brand = bool(strangers)
    else:
        print("  WARN: no brand toolkit and no tokens.json - build the design system "
              "(brand-system: brand.py build) so the PDF's fonts can be checked.", file=sys.stderr)

    if off_brand:
        print("  Something fell back to a system face - the file will not look the same on "
              "another machine.", file=sys.stderr)
        uncovered = uncovered_characters(markup)
        if uncovered:
            print("  the character(s) no embedded face can draw - this is what pulled the "
                  "system font in:", file=sys.stderr)
            for row in uncovered:
                print(f"    {row}", file=sys.stderr)
            print("  Rewrite the copy without them (a word instead of an arrow), or widen the "
                  "subset in the brand-system build and re-inline the BRAND block.",
                  file=sys.stderr)
        else:
            print("  (no uncovered character found - check the weights asked for against "
                  "tokens.json embedded_weights; install fonttools if it is missing)",
                  file=sys.stderr)

    print("\nOpen it and compare it against the HTML side by side before sending. Letters "
          "must join, text must run in the note's direction, the cards must still be two-up, "
          "and the background must be the brand's wash (flat for some brands) - compare it "
          "against the HTML, not against an expectation.")
    print("compare-pdf-to-html.py does that comparison numerically.")
    if off_brand:
        # Rule 5: exit codes reflect failures. A PDF in a system face is not the
        # document that was approved, however plausible it looks.
        print("FAIL: off-brand font(s) in the PDF (see above).", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
